### PR TITLE
Add http_proxy, ftp_proxy, and urllist parameters

### PR DESCRIPTION
**Pull request by alexjfisher**
This PR builds upon/supercedes the work done in https://github.com/meltwater/puppet-cpan/pull/36

It fixes a couple of issues with the new proxy parameters and adds rspec tests for them.
It also adds a new `urllist` parameter.  I found I needed to modify `urllist` as I've only got an http_proxy and, by default, downloads from CPAN were attempted over ftp.
See https://github.com/meltwater/puppet-cpan/commit/442703bc52b673659ec7eda2854383d5a62f3bff commit message for more details.

### CODE REVIEW

**Comment by alexjfisher** [comment]
@salimane Does this look ok?

**Comment by alexjfisher** [comment]
@salimane Thanks!  I've just noticed that in June you added a deprecated notice to this module.  How would you feel about the [Vox Pupuli](https://voxpupuli.org/docs/) project maintaining this module?

**Comment by salimane** [comment]
@alexjfisher we are discussing about this internally. I will ping you when we reach a decision :)

**Comment by alexjfisher** [comment]
@salimane To be clear, original authors retain all copyright and new contributors aren't asked to sign a CLA or anything like that.  We also wouldn't remove any transfer notice section you add to the README for example.  But basically, it's much nicer to have a github repo transferred rather than forked.  That way, all the issues and PRs (open and closed) get moved to their new home.

**Pull request merged**
